export const tools = [
    {src: "/img/tools/vc.png", title: "Visual Composer", url: "https://dev.visualcomposer.com/"},
    {src: "/img/tools/contact-7.png", title: "Contact Form 7", url: "https://contactform7.com/docs/"},
    {src: "/img/tools/wpml.png", title: "WPML", url: "https://wpml.org/documentation/"},
    {src: "/img/tools/code.png", title: "No Coding Required", url: ""},
    {src: "/img/tools/document.png", title: "Well Documented", url: ""},
    {src: "/img/tools/speed.png", title: "Speed Optimized", url: ""},
    {src: "/img/tools/w3c-validation.png", title: "W3C Validation", url: "https://www.w3.org/TR/"},
    {src: "/img/tools/responsive.png", title: "Fully Responsive", url: ""},
    {src: "/img/tools/code.png", title: "Clean Code", url: ""},
    {src: "/img/tools/google-font.png", title: "Google Font", url: "https://fonts.google.com/"},
    {src: "/img/tools/magnific-popup.png", title: "Magnific Popup", url: "https://dimsemenov.com/plugins/magnific-popup/documentation.html"},
    {src: "/img/tools/bootstrap.png", title: "Bootstrap V4", url: "https://getbootstrap.com/docs/4.0/getting-started/introduction/"},
    {src: "/img/tools/slick.png", title: "Slick Slider", url: "https://bezramok-tlt.ru/blog/posts/slick-slider-ustanovka-nastrojka-primery-i-dokumentaciya"},
    {src: "/img/tools/flat-icon.png", title: "Flat Icon", url: "https://www.flaticon.com/"},
    {src: "/img/tools/fontaersome.png", title: "Fontawesome Icon", url: "https://fontawesome.com/icons"},
    {src: "/img/tools/html5.png", title: "Html5", url: "https://www.w3schools.com/html/html_intro.asp"},
    {src: "/img/tools/css3.png", title: "Css3", url: "https://www.w3schools.com/cssref/index.php"},
    {src: "/img/tools/jquery.png", title: "Jquery", url: "https://api.jquery.com/"},
]