import type { Metadata } from "next";
import { Poppins, Rubik } from "next/font/google";
import { ThemeProvider } from "@/utils/material-tailwind";
import "./globals.css";

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
  });

  const rubik = Rubik ({
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800", "900"]
  })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={`${poppins.className} ${rubik.className}`}>{children}</body>
      </ThemeProvider>
    </html>
  );
}
